### ISSUE TITLE
Unable to select a market in Quest Valuation Tool

### ISSUE THREAD

**Issue by UGuntupalli** [snl-quest/snl-quest#23]
After setting up Quest, no matter how many times, I try, I am unable to select a market area. After selecting a market area, I see nothing happens, no message is printed on my Python IDE either. I have closed the application couple of times and reopened with the same result

![image](https://user-images.githubusercontent.com/47903157/79787503-f65e5180-82fb-11ea-92e2-bbd27cb50ca2.png)

**Comment by rconcep** [comment]
Hello,

Options for market areas in QuESt Valuation appear based on the data downloaded to your data bank. You will need to acquire data through the QuESt Data Manager application first. Once you have downloaded data for a particular market area, options to use that data should appear throughout the QuESt Valuation interfaces.

For first time users, we recommend checking out the quick tutorial/tour at the top of the QuESt index screen.

Best,
Ricky

**Comment by UGuntupalli** [comment]
Got it Ricky. Thanks
