### ISSUE TITLE
GUI flashing and lagging, leaving all the images on the window

### ISSUE THREAD

**Issue by luciaxu2010** [snl-quest/snl-quest#24]
Hi Ricky, 

Thank you for your work and sharing!
I am using Spyder 4.0.1, Python 3.7 with kivy 1.11.1. I am able to run main modules. But the GUI is  experiencing serious lagging and flashing (usually appears duplicate image that flashes); the mouse is also not able to click the tabs; When accidentally clicked the "correct" tabs, it leaves every images on the top of black background. This makes me not able to use the tool at all.

May I ask is there anything I can do to fix this?
Thanks!

Lucia

**Comment by luciaxu2010** [comment]
FYI this is what I can do but can't read any words due to flashing and duplicates:
[INFO   ] [Logger      ] Record log in C:\Users\admin\.kivy\logs\kivy_20-04-23_5.txt
[INFO   ] [Kivy        ] v1.11.1
[INFO   ] [Kivy        ] Installed at "C:\Users\admin\anaconda3\lib\site-packages\kivy\__init__.py"
[INFO   ] [Python      ] v3.7.6 (default, Jan  8 2020, 20:23:39) [MSC v.1916 64 bit (AMD64)]
[INFO   ] [Python      ] Interpreter at "C:\Users\admin\anaconda3\python.exe"
[INFO   ] [Factory     ] 184 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] GLEW initialization succeeded
[INFO   ] [GL          ] Backend used <glew>
[INFO   ] [GL          ] OpenGL version <b'4.6.0 - Build 26.20.100.6860'>
[INFO   ] [GL          ] OpenGL vendor <b'Intel'>
[INFO   ] [GL          ] OpenGL renderer <b'Intel(R) UHD Graphics 630'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 6
[INFO   ] [GL          ] Shading version <b'4.60 - Build 26.20.100.6860'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [GL          ] NPOT texture support is available
[INFO   ] [GL          ] Unpack subimage support is available
libpng warning: Interlace handling should be turned on when using png_read_image
[INFO   ] [Base        ] Start application main loop
[INFO   ] [Loader      ] using a thread pool of 2 workers
[INFO   ] [WindowSDL   ] exiting mainloop and closing.
[INFO   ] [Base        ] Leaving application in progress...

**Comment by rconcep** [comment]
Hi Lucia,

From your log it looks like you're using a computer with an integrated graphics processor. If you're using a laptop, are you able to run the GUI on an external display/monitor?

Ricky

**Comment by luciaxu2010** [comment]
Hi Ricky,

Yes, restart and the external display worked! 
Thank you!

Lucia
