### ISSUE TITLE
EnergyPlus not found issue with QuESt performance (v1.6-beta)

### ISSUE THREAD

**Issue by atribera** [snl-quest/snl-quest#35]
I am getting the following error while trying to run QuESt performance using the "Performance Simulation" button: 

**EnergyPlus not found. Please visit help tab to configure EnergyPlus on your machine.**

Note: I have downloaded and moved the software to the QuESt directory on my computer and have renamed it to "energyplus" as instructed in the help tab.

**Comment by wpo14** [comment]
Another module was missing (eppy) and the EnergyPlus popup was triggered. 

I've amended the code to change the popup based upon what module is missing.
