### ISSUE TITLE
Valuation app error while using SPP data

### ISSUE THREAD

**Issue by atribera** [snl-quest/snl-quest#37]
This error comes up while trying to run arbitrage and regulation with the valuation tool with SPP data (I downloaded January 2021 data) in the console:

**At least one of the array-like parameter objects is not the expected length. (It should match the length of the price_electricity object.)**

Arbitrage alone seems to work fine.

**Comment by AlvaroFurlani** [comment]
@atribera this issue should be fixed in the latest v1.6-beta. Please try again and close the issue if it works properly for you now.

Note: you may need to manually delete the file valuation_dms.p to make sure that the changes take effect.

**Comment by atribera** [comment]
It works. I had to delete the `valuation_dms.p` file for it to work.
